language: ruby
rvm:
  - 2.7.2
script:
  bundle exec jekyll build
deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
